module.exports =
  "button-about": "About Us"
  "button-technologies": "Technologes"
  "button-order": "Order"
  "button-contacts": "Contact Us"
  "button-settings": "Settings"
  "button-orders": "Orders"
  "button-menu-menu": "Menu"
  "firm-name": "IVAS-TECH"
  "web-page": "Stencils"
