module.exports =
  "button-about": "За нас"
  "button-technologies": "Технологии"
  "button-order": "Поръчай"
  "button-contacts": "Контакти"
  "button-settings": "Настройки"
  "button-orders": "Поръчки"
  "button-menu-menu": "Меню"
  "firm-name": "ИВАС-ТЕХ"
  "web-page": "Стенсили"
