module.exports =
  "button-register": "Регистрация"
  "button-close": "Затвори"
  "button-cancel": "Отказ"
  "label-email": "Имейл адрес"
  "label-password": "Парола"
  "label-repassword": "Потвърди паролата"
  "error-email-email": "Невалиден имейл адрес"
  "error-email-taken": "Този емейл адрес е зает"
  "error-email-required": "Имейл адрес е задължителeн"
  "error-password-minlength": "Паролата трябва да е поне 6 символа дълга"
  "error-password-maxlength": "Паролата трябва да е по-къса от 36 символа"
  "error-password-required": "Паролата е задължителна"
  "error-repassword-pattern": "Потвърдената парола е различна от паролата"
  "error-repassword-required": "Потвърждаването на паролата е задължително"
