module.exports = {
  "button-login": "Log In"
  "button-register": "Register"
  "button-close": "Close"
  "button-cancel": "Cancel"
  "button-tryAgain": "Try again"
  "button-logout": "Logout"
  "checkbox-stay-login": "Keep me logged in"
  "label-email": "Email"
  "label-password": "Password"
  "label-repassword": "Re-Password"
  "error-email-email": "Invalid Email"
  "error-email-taken": "This email is taken"
  "error-email-required": "Email is required"
  "error-password-minlength": "Password must be atleast 6 symbols "
  "error-password-maxlength": "Password must be less than 36 symbols"
  "error-password-required": "Password is required"
  "error-repassword-pattern": "Re-Password doen't match password"
  "error-repassword-required": "Re-Password is required"
}
