module.exports =  {
  "button-login": "Вход"
  "button-register": "Регистрация"
  "button-close": "Затвори"
  "label-email": "Елкетронна поща"
  "label-password": "Парола"
  "label-repassword": "Потвърди паролата"
  "button-tryAgain": "Опитай отново"
  "button-cancel": "Отказ"
  "error-email-email": "Невалиден имейл адрес"
  "error-email-taken": "Този емейл адрес е зает"
  "error-email-required": "Елкетронна поща е задължителна"
  "error-password-minlength": "Паролата трябва да е поне 6 символа дълга"
  "error-password-maxlength": "Паролата трябва да е по-къса от 36 символа"
  "error-password-required": "Паролата е задължителна"
  "error-repassword-pattern": "Потвърдената парола е различна от паролата"
  "error-repassword-required": "Потвърждаването на паролата е задължително"
}
