module.exports =  {
  "button-login": "Вход"
  "button-register": "Регистрация"
  "button-close": "Затвори"
  "button-cancel": "Отказ"
  "button-logout": "Изход"
  "button-tryAgain": "Опитай отново"
  "button-ok": "Добре"
  "checkbox-stay-login": "Запомни ме"
  "label-email": "Имейл адрес"
  "label-password": "Парола"
  "label-repassword": "Потвърди паролата"
  "title-wrong-login": "Грешен имейл адрес или парола"
  "error-email-email": "Невалиден имейл адрес"
  "error-email-taken": "Този емейл адрес е зает"
  "error-email-required": "Имейл адреса е задължителна"
  "error-password-minlength": "Паролата трябва да е поне 6 символа дълга"
  "error-password-maxlength": "Паролата трябва да е по-къса от 36 символа"
  "error-password-required": "Паролата е задължителна"
  "error-repassword-pattern": "Потвърдената парола е различна от паролата"
  "error-repassword-required": "Потвърждаването на паролата е задължително"
}
